### ISSUE TITLE
Cannot build examples for 2.17.8

### ISSUE THREAD

**Issue by fschon** [openmdx/openmdx-example#2]
The build commands for the examples seem to be out of date.
The link to create an openmdx SDK for eclipse is broken (https://github.com/openmdx/openmdx-documentation/blob/master/Sdk/StepByStepEclipse.md)
I have assumed that using the "gradle eclipse" command in the openmdx dir is sufficient?
However there is no openmdx/distribution directory and so the examples ant build file fails

**Comment by javac9** [comment]
Any updates on this issue?

**Comment by wfro64** [comment]
In the meantime the mentioned guide was replaced by:
* https://github.com/openmdx/openmdx-documentation/blob/master/Sdk/BuildFromSource.md
* https://github.com/openmdx/openmdx-documentation/blob/master/Sdk/Examples.md

The Workshop guide still needs to be updated so that it works with the gradle based build:
* https://github.com/openmdx/openmdx-documentation/blob/master/Sdk/Workshop.md

**Comment by wfro64** [comment]
https://github.com/openmdx/openmdx-documentation/tree/master/Sdk is now up-to-date.
